version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.production

  web:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV}
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec puma -C config/puma.rb

volumes:
  pgdata:
