default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "rails_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "db") %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] %>
