default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "1234" %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>

development:
  <<: *default
  database: db

test:
  <<: *default
  database: rails_test

production:
  url: <%= ENV["DATABASE_URL"] %>
